version: "3.9"

services:
  backend:
    image: ghcr.io/gradimbuyi/wealthtrackit-backend:latest
    container_name: w-backend
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "5000"
    networks:
      - w-network

  frontend:
    image: ghcr.io/gradimbuyi/wealthtrackit-frontend:latest
    container_name: w-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - w-network

networks:
  w-network:
    driver: bridge
